### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by vicnala** [DiscoverMeteor/DiscoverMeteorStatic#32]
Hi,

I was trying to update the Es translation but deployment process failed for the  `jp` repo.
I ran locally and saw that something was very wrong with the `jp` source files so, trying to isolate the problem I removed the `jp` submodule following this:
http://stackoverflow.com/questions/1260748/how-do-i-remove-a-git-

Now, If running locally with middleman everything works, but deployment process still fails again saying this:
> remote: No submodule mapping found in .gitmodules for path 'source/chapters/jp'

But, there is no path and no mention to `jp` in *this* repo by now.

I don't know what to do.

**Comment by vicnala** [comment]
Fixed 11c5851208b6a744f285d97df41ace38fb22a454

**Comment by SachaG** [comment]
For what it's worth this is the only thing that worked to fix that issue: http://stackoverflow.com/a/20134575/649299

**Comment by vicnala** [comment]
Ok, so it's about re-deploy everything.

**Comment by SachaG** [comment]
Yes, I'm running a script to do that now. It'll take a while…
